### ISSUE TITLE
Incorrect dependencies

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/simple-parsing-feedstock#21]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

There are several issues with the dependencies for this package, at least since v0.1.0.  On conda-forge, this package shows python >=3.6 as a dependency.  However, according to the project's [setup.py](https://github.com/lebrice/SimpleParsing/blob/v0.1.0/setup.py) file, it requires python >=3.7.  Additionally, on conda-forge, this package shows `typing_inspect` as a dependency.  However, according to the package's [requirements.txt](https://github.com/lebrice/SimpleParsing/blob/v0.1.0/requirements.txt), it actually requires `typing_extensions` instead.  Furthermore, later versions of this package require later versions of `typing_extensions`.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by thewchan** [comment]
Addressed in #22
